# Generated by Django 3.0.6 on 2020-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
