# Generated by Django 3.0.6 on 2020-05-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200216_1234'),
        ('products', '0009_auto_20200505_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('product_varaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product_Variant')),
            ],
        ),
    ]
