# Generated by Django 3.0.6 on 2020-07-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_brand'),
        ('accounts', '0002_auto_20200216_1234'),
        ('recommenderSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField()),
                ('rated', models.BooleanField()),
                ('purchase', models.BooleanField()),
                ('coll_date', models.DateTimeField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.DeleteModel(
            name='recom_user_data',
        ),
    ]
