# Generated by Django 3.0.6 on 2020-08-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderSystem', '0002_auto_20200729_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recommendProd',
        ),
    ]
