# Generated by Django 3.0.6 on 2020-08-11 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderSystem', '0003_delete_recommendprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='activity_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 19, 10, 20, 479505)),
        ),
    ]
