# Generated by Django 3.0.6 on 2020-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderSystem', '0004_auto_20200811_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='activity_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
