# Generated by Django 3.0.6 on 2020-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='sku',
            field=models.CharField(default='', max_length=255),
        ),
    ]
