# Generated by Django 3.0.6 on 2020-08-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200805_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
