# Generated by Django 3.0.6 on 2020-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_rating',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
